apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xpyxt0gbi-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c1f1827773.zivp.p3.openshiftapps.com/rhtap/rhtap-qe:b1f79833cdc291ea6ecff9dab180b8710b05756f@sha256:00bccc17f875b8ecc667fb3107afc73677fe5d0971fe4f3112179dddcd36d2a1
          name: container-image
